[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx tsc --skipLibCheck; rm -rf dist/admin-panel && cp -r admin-panel dist/admin-panel"

[deploy]
startCommand = "cd backend && node dist/index.js"
restartPolicyType = "on_failure"

[nixpacks]
providers = ["node"]

[nixpacks.variables]
NODE_VERSION = "20"
